# Steam Oyun Verisinin İlk İncelemesi

Bu notebookta Steam oyun veri setinin sütun yapısı incelenmekte ve veri kalitesiyle ilgili ilk kontroller yapılmaktadır.

In [1]:
import pandas as pd

In [2]:
dosya_yolu = "../data/raw/games.csv"

ornek_veri = pd.read_csv(dosya_yolu, nrows=5)
ornek_veri

,AppID,Name,Release date,Estimated owners,Peak CCU,Required age,Price,DiscountDLC count,About the game,Supported languages,...,Average playtime two weeks,Median playtime forever,Median playtime two weeks,Developers,Publishers,Categories,Genres,Tags,Screenshots,Movies
2539430,Black Dragon Mage Playtest,"Aug 1, 2023",0 - 0,0,0,0.00,0,0,NaN,[],...,0,0,0,NaN,NaN,NaN,NaN,NaN,https://shared.akamai.steamstatic.com/store_it...,NaN
496350,Supipara - Chapter 1 Spring Has Come!,"Jul 29, 2016",0 - 20000,0,0,5.24,65,0,"Springtime, April: when the cherry trees come ...",['English'],...,0,8,0,minori,MangaGamer,"Single-player,Steam Trading Cards,Steam Cloud,...",Adventure,"Adventure,Visual Novel,Anime,Cute",https://shared.akamai.steamstatic.com/store_it...,NaN
1034400,Mystery Solitaire The Black Raven,"May 6, 2019",0 - 20000,0,0,4.99,0,0,"Immerse yourself in the most beloved, mystical...","['English', 'French', 'German', 'Russian']",...,0,0,0,Somer Games,8floor,"Single-player,Family Sharing",Casual,"Casual,Card Game,Solitaire,Puzzle,Hidden Objec...",https://shared.akamai.steamstatic.com/store_it...,NaN
3292190,버튜버 파라노이아 - Vtuber Paranoia,"Oct 31, 2024",0 - 20000,1,0,8.99,0,1,"synopsis 'Hello, I'm Hiyoro, a new YouTuber!' ...",['Korean'],...,0,0,0,유진게임즈,유진게임즈,"Single-player,Steam Achievements,Family Sharing","Casual,Indie,Simulation",NaN,https://shared.akamai.steamstatic.com/store_it...,NaN
3631080,Maze Quest VR,"Apr 24, 2025",0 - 20000,0,0,4.99,0,0,Its not just a Maze; its a Quest! Enter the ca...,['English'],...,0,0,0,Reality Expanded LLC,Reality Expanded LLC,"Single-player,VR Only,Steam Leaderboards,Famil...","Action,Early Access",NaN,https://shared.akamai.steamstatic.com/store_it...,NaN

In [3]:
ornek_veri.columns

Index(['AppID', 'Name', 'Release date', 'Estimated owners', 'Peak CCU',
       'Required age', 'Price', 'DiscountDLC count', 'About the game',
       'Supported languages', 'Full audio languages', 'Reviews',
       'Header image', 'Website', 'Support url', 'Support email', 'Windows',
       'Mac', 'Linux', 'Metacritic score', 'Metacritic url', 'User score',
       'Positive', 'Negative', 'Score rank', 'Achievements', 'Recommendations',
       'Notes', 'Average playtime forever', 'Average playtime two weeks',
       'Median playtime forever', 'Median playtime two weeks', 'Developers',
       'Publishers', 'Categories', 'Genres', 'Tags', 'Screenshots', 'Movies'],
      dtype='object')

In [4]:
ornek_veri.shape

(5, 39)

In [5]:
ornek_veri.dtypes

AppID                          object
Name                           object
Release date                   object
Estimated owners                int64
Peak CCU                        int64
Required age                  float64
Price                           int64
DiscountDLC count               int64
About the game                 object
Supported languages            object
Full audio languages           object
Reviews                       float64
Header image                   object
Website                        object
Support url                    object
Support email                  object
Windows                          bool
Mac                              bool
Linux                            bool
Metacritic score                int64
Metacritic url                float64
User score                      int64
Positive                        int64
Negative                        int64
Score rank                    float64
Achievements                    int64
Recommendations                 int64
Notes                          object
Average playtime forever        int64
Average playtime two weeks      int64
Median playtime forever         int64
Median playtime two weeks       int64
Developers                     object
Publishers                     object
Categories                     object
Genres                         object
Tags                           object
Screenshots                    object
Movies                        float64
dtype: object

In [6]:
sutunlar = pd.read_csv(dosya_yolu, nrows=0).columns.tolist()

birlesik_sutun = sutunlar.index("DiscountDLC count")
sutunlar[birlesik_sutun:birlesik_sutun + 1] = ["Discount", "DLC count"]

duzeltilmis_ornek = pd.read_csv(
    dosya_yolu,
    skiprows=1,
    names=sutunlar,
    nrows=5
)

duzeltilmis_ornek

,AppID,Name,Release date,Estimated owners,Peak CCU,Required age,Price,Discount,DLC count,About the game,...,Average playtime two weeks,Median playtime forever,Median playtime two weeks,Developers,Publishers,Categories,Genres,Tags,Screenshots,Movies
0,2539430,Black Dragon Mage Playtest,"Aug 1, 2023",0 - 0,0,0,0.00,0,0,NaN,...,0,0,0,NaN,NaN,NaN,NaN,NaN,https://shared.akamai.steamstatic.com/store_it...,NaN
1,496350,Supipara - Chapter 1 Spring Has Come!,"Jul 29, 2016",0 - 20000,0,0,5.24,65,0,"Springtime, April: when the cherry trees come ...",...,0,8,0,minori,MangaGamer,"Single-player,Steam Trading Cards,Steam Cloud,...",Adventure,"Adventure,Visual Novel,Anime,Cute",https://shared.akamai.steamstatic.com/store_it...,NaN
2,1034400,Mystery Solitaire The Black Raven,"May 6, 2019",0 - 20000,0,0,4.99,0,0,"Immerse yourself in the most beloved, mystical...",...,0,0,0,Somer Games,8floor,"Single-player,Family Sharing",Casual,"Casual,Card Game,Solitaire,Puzzle,Hidden Objec...",https://shared.akamai.steamstatic.com/store_it...,NaN
3,3292190,버튜버 파라노이아 - Vtuber Paranoia,"Oct 31, 2024",0 - 20000,1,0,8.99,0,1,"synopsis 'Hello, I'm Hiyoro, a new YouTuber!' ...",...,0,0,0,유진게임즈,유진게임즈,"Single-player,Steam Achievements,Family Sharing","Casual,Indie,Simulation",NaN,https://shared.akamai.steamstatic.com/store_it...,NaN
4,3631080,Maze Quest VR,"Apr 24, 2025",0 - 20000,0,0,4.99,0,0,Its not just a Maze; its a Quest! Enter the ca...,...,0,0,0,Reality Expanded LLC,Reality Expanded LLC,"Single-player,VR Only,Steam Leaderboards,Famil...","Action,Early Access",NaN,https://shared.akamai.steamstatic.com/store_it...,NaN

In [7]:
duzeltilmis_ornek.shape

(5, 40)

In [8]:
duzeltilmis_ornek[
    ["AppID", "Name", "Release date", "Price", "Discount", "DLC count"]
]

,AppID,Name,Release date,Price,Discount,DLC count
0,2539430,Black Dragon Mage Playtest,"Aug 1, 2023",0.00,0,0
1,496350,Supipara - Chapter 1 Spring Has Come!,"Jul 29, 2016",5.24,65,0
2,1034400,Mystery Solitaire The Black Raven,"May 6, 2019",4.99,0,0
3,3292190,버튜버 파라노이아 - Vtuber Paranoia,"Oct 31, 2024",8.99,0,1
4,3631080,Maze Quest VR,"Apr 24, 2025",4.99,0,0

## CSV başlık kontrolü

İlk incelemede `Discount` ve `DLC count` sütunlarının başlıkta birleştiği görüldü.
Bu nedenle veri satırları yanlış sütunlarla eşleşiyordu. Birleşmiş başlık iki ayrı
sütuna ayrıldıktan sonra örnek veri 40 sütunla doğru şekilde okundu.

In [9]:
kullanilacak_sutunlar = [
    "AppID",
    "Name",
    "About the game",
    "Price",
    "Windows",
    "Mac",
    "Linux",
    "Supported languages",
    "Categories",
    "Genres"
]

satir_sayisi = 0
eksik_degerler = pd.Series(0, index=kullanilacak_sutunlar)

for parca in pd.read_csv(
    dosya_yolu,
    skiprows=1,
    names=sutunlar,
    usecols=kullanilacak_sutunlar,
    chunksize=10000
):
    satir_sayisi += len(parca)
    eksik_degerler += parca.isna().sum()

print("Toplam satır sayısı:", satir_sayisi)
eksik_degerler

Toplam satır sayısı: 125855

AppID                     0
Name                      1
About the game         8462
Price                     0
Windows                   0
Mac                       0
Linux                     0
Supported languages       0
Categories             8966
Genres                 8423
dtype: int64

In [10]:
eksik_ozeti = pd.DataFrame({
    "Eksik değer": eksik_degerler,
    "Eksik oranı (%)": (eksik_degerler / satir_sayisi * 100).round(2)
})

eksik_ozeti

                     Eksik değer  Eksik oranı (%)
AppID                          0             0.00
Name                           1             0.00
About the game              8462             6.72
Price                          0             0.00
Windows                        0             0.00
Mac                            0             0.00
Linux                          0             0.00
Supported languages            0             0.00
Categories                  8966             7.12
Genres                      8423             6.69

## İlk değerlendirme

Veri setinde toplam 125.855 oyun kaydı bulunmaktadır. Fiyat, işletim sistemi ve
desteklenen dil alanlarında eksik değer görülmemiştir. Oyun açıklaması, kategori
ve tür alanlarında ise eksik kayıtlar bulunmaktadır. Bu alanlar anlamsal aramada
kullanılacağı için veri temizleme aşamasında ayrıca değerlendirilecektir.

In [11]:
eksik_oyun_listesi = []

for parca in pd.read_csv(
    dosya_yolu,
    skiprows=1,
    names=sutunlar,
    usecols=kullanilacak_sutunlar,
    chunksize=10000
):
    eksik_mi = parca[
        ["About the game", "Categories", "Genres"]
    ].isna().any(axis=1)

    eksik_kayitlar = parca.loc[
        eksik_mi,
        ["AppID", "Name", "About the game", "Categories", "Genres"]
    ].copy()

    eksik_oyun_listesi.append(eksik_kayitlar)

eksik_oyunlar = pd.concat(eksik_oyun_listesi, ignore_index=True)

print("En az bir alanı eksik oyun sayısı:", len(eksik_oyunlar))
eksik_oyunlar.head(20)

En az bir alanı eksik oyun sayısı: 9568

,AppID,Name,About the game,Categories,Genres
0,2539430,Black Dragon Mage Playtest,NaN,NaN,NaN
1,1946890,Codename: Warlock Playtest,NaN,NaN,NaN
2,2349750,CyberVault Playtest,NaN,NaN,NaN
3,2628280,A Night In Omar's Burger Playtest,NaN,NaN,NaN
4,2689730,Dark and Deep Playtest,NaN,NaN,NaN
5,1871390,VSS - Virtual Streaming Software,Virtual Streaming Software or VSS is a Live2D ...,NaN,"Animation & Modeling,Video Production,Early Ac..."
6,2782210,Bill's Misfortune Playtest,NaN,NaN,NaN
7,3664570,QUADRA CLASH Playtest,NaN,NaN,NaN
8,3581240,Descendance Playtest,NaN,NaN,NaN
9,1549730,Red Solstice 2: Survivors Playtest,NaN,NaN,NaN
10,1170750,MOR...E TRAINER (Learning Morse Code),SIMPLE AND EASY LEARNING MORSE CODE Morse code...,NaN,Education
11,1639330,Pain Party Playtest,NaN,NaN,NaN
12,3392860,Mechanical Pulse Playtest,NaN,NaN,NaN
13,1106180,SpriteStack,-- 2021 Upcoming update -- One liner about NEX...,NaN,"Animation & Modeling,Design & Illustration,Gam..."
14,3085750,1971 Playtest,NaN,NaN,NaN
15,3973110,Trickster Trove Playtest,NaN,NaN,NaN
16,919330,Ghost in the pool,NaN,"Single-player,Steam Achievements,Partial Contr...","Adventure,Indie"
17,1855530,From Warrior to Hero (Idle 3D RPG) Playtest,NaN,NaN,NaN
18,1555470,Zombie Blender,Zombie Blender is a retro indie 2D shooter whe...,"Single-player,Family Sharing",NaN
19,2434250,Biofusion Multiplayer Playtest,NaN,VR Only,NaN

In [12]:
playtest_kayitlari = eksik_oyunlar[
    eksik_oyunlar["Name"]
    .fillna("")
    .str.contains("Playtest", case=False)
]

print("Eksik alanı bulunan Playtest sayısı:", len(playtest_kayitlari))
playtest_kayitlari[["AppID", "Name"]].head(20)

Eksik alanı bulunan Playtest sayısı: 8133

      AppID                                         Name
0   2539430                   Black Dragon Mage Playtest
1   1946890                   Codename: Warlock Playtest
2   2349750                          CyberVault Playtest
3   2628280            A Night In Omar's Burger Playtest
4   2689730                       Dark and Deep Playtest
6   2782210                   Bill's Misfortune Playtest
7   3664570                        QUADRA CLASH Playtest
8   3581240                         Descendance Playtest
9   1549730           Red Solstice 2: Survivors Playtest
11  1639330                          Pain Party Playtest
12  3392860                    Mechanical Pulse Playtest
14  3085750                                1971 Playtest
15  3973110                     Trickster Trove Playtest
17  1855530  From Warrior to Hero (Idle 3D RPG) Playtest
19  2434250               Biofusion Multiplayer Playtest
20  3851530                           Crossings Playtest
21  2205440                      Project OutFox Playtest
22  1761940                         MonsterCare Playtest
23  3058300                       Airsoft Range Playtest
24  2645020                          Joker Bass Playtest

## Eksik kayıtların incelenmesi

Açıklama, kategori veya tür alanlarından en az biri eksik olan 9.568 kayıt
bulunmaktadır. Bu kayıtların 8.133 tanesinin adında `Playtest` ifadesi yer
almaktadır. Eksik kayıtların büyük bölümünün test sürümlerinden oluştuğu
görülmüştür.

Eksik olan bütün kayıtlar doğrudan silinmeyecektir. Playtest kayıtları ile normal
oyunlar veri temizleme aşamasında ayrı ayrı değerlendirilecektir.

In [13]:
kontrol_sutunlari = [
    "Name",
    "About the game",
    "Categories",
    "Genres"
]

oyun_kontrol = pd.read_csv(
    dosya_yolu,
    skiprows=1,
    names=sutunlar,
    usecols=kontrol_sutunlari
)

playtestler = oyun_kontrol[
    oyun_kontrol["Name"].str.contains(
        "Playtest", 
        case=False, 
        na=False 
    )
]

normal_oyunlar = oyun_kontrol[
    oyun_kontrol["Name"].str.contains(
        "Playtest",
        case=False,
        na=False
    ) == False
]

kullanilabilir_oyunlar = normal_oyunlar.dropna(
    subset=[
        "Name",
        "About the game",
        "Categories",
        "Genres"
    ]
)

print("Toplam kayıt sayısı:", len(oyun_kontrol))
print("Toplam Playtest sayısı:", len(playtestler))
print("Playtest olmayan kayıt sayısı:", len(normal_oyunlar))
print("Ön kullanılabilir oyun sayısı:", len(kullanilabilir_oyunlar))
print(
    "Eksik alanı bulunan normal kayıt:",
    len(normal_oyunlar) - len(kullanilabilir_oyunlar)
)

Toplam kayıt sayısı: 125855
Toplam Playtest sayısı: 8139
Playtest olmayan kayıt sayısı: 117716
Ön kullanılabilir oyun sayısı: 116281
Eksik alanı bulunan normal kayıt: 1435

## Ön kullanılabilir oyun sayısı

Veri setinde toplam 8.139 Playtest kaydı bulunduğu görülmüştür. Playtest kayıtları
çıkarıldığında 117.716 kayıt kalmaktadır. Oyun adı, açıklama, kategori ve tür
alanları eksik olan normal kayıtlar da çıkarıldığında ön kullanılabilir oyun
sayısı 116.281 olmaktadır.

Bu sayı son temiz veri sayısı değildir. Desteklenen dil alanındaki boş değerler
ve tekrar eden oyun kimlikleri ayrıca kontrol edilecektir.

In [14]:
dil_ve_id_kontrol = pd.read_csv(
    dosya_yolu,
    skiprows=1,
    names=sutunlar,
    usecols=[
        "AppID",
        "Supported languages"
    ]
)

bos_dil_kayitlari = dil_ve_id_kontrol[
    dil_ve_id_kontrol["Supported languages"] == "[]"
]

tekrar_eden_appid = dil_ve_id_kontrol[
    "AppID"
].duplicated().sum()

print(
    "Desteklenen dil listesi boş olan kayıt:",
    len(bos_dil_kayitlari)
)

print(
    "Tekrar eden AppID sayısı:",
    tekrar_eden_appid
)

print(
    "Benzersiz AppID sayısı:",
    dil_ve_id_kontrol["AppID"].nunique()
)

Desteklenen dil listesi boş olan kayıt: 8391
Tekrar eden AppID sayısı: 0
Benzersiz AppID sayısı: 125855

## Dil ve oyun kimliği kontrolü

Desteklenen dil alanında eksik değer görülmemesine rağmen 8.391 kaydın boş liste
olarak tutulduğu belirlenmiştir. Bu kayıtlar dil filtresinde kullanılamayacağı
için veri temizleme aşamasında ayrıca değerlendirilecektir.

AppID alanında tekrar eden bir değere rastlanmamıştır. Veri setindeki 125.855
kaydın tamamı benzersiz bir oyun kimliğine sahiptir.